### ISSUE TITLE
In /contributors check

### ISSUE THREAD

**Issue by jlord** [jlord/git-it#111]
Unsure why at yesterday's event someone was getting an error, so look back into this logic.

**Comment by osteenbergen** [comment]
Got an error during the contributors check
```
git-it verify
Verifying "BRANCHES AREN'T JUST FOR BIRDS"...

ACTUAL                             EXPECTED
------                             --------
"{ [Error: Command failed: ] killed: false, code: 1, signal: null }" != "Found branch as expected!"    
""                              != "Changes have been pushed!"    
null                            != ""                             
# FAIL
```
The cause of the error is that ```git config user.username``` wasn't set to my username, but empty. My git is configured using the global config, instead of user.username I use user.email

Maybe the verify step should report a message with "Please set your username with..."
