### ISSUE TITLE
The `node` program is `nodejs` on Debian-based systems

### ISSUE THREAD

**Issue by ramsey** [jlord/git-it#118]
We ran into this issue in a Patchwork training session with a user on Ubuntu 14.04. The shebang line in the `git-it` script is:

```
#!/usr/bin/env node
```

When running `git-it`, it was exiting with a 1 error code. We scratched our heads for a while until we took a look at the code and remembered that the correct program on Ubuntu is `nodejs` and not `node`, which is a ham radio application (or something like that).

To fix it for the user, we changed the line to:

```
#!/usr/bin/env nodejs
```

Obviously, this isn't an acceptable change to the program, since that would break it for everyone else, but it would be good to find a solution that will work for everyone.

**Comment by jlord** [comment]
In the new [Git-it Electron](https://github.com/jlord/git-it-electron) node comes bundled, woot! Thanks y'all!
