### ISSUE TITLE
Up our docs game for Windows users

### ISSUE THREAD

**Issue by gpadak** [jlord/git-it#127]
Some windows users struggle getting started after they download the .msi for Node. Depending on OS, it may install in some different places and can be hard enough to find that [someone wrote a stackoverflow article about it](http://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows). Once the user finds npm, installing the git-it package is easy enough.

In the case I was mentoring that was just the beginning of the fun. After we found where git-it landed, running the program resulted in a javascript error. We worked around this by adding both node and git-it to the system path (there's probably another way). 

We also had a couple up-front struggles with getting Git itself to run from anywhere. To get around that we opted to just use the Git shell for the exercise.

In any event when I get a free bit I'll go ahead and open up a PR with some Windows-specific getting started documentation.

**Comment by jlord** [comment]
Sooooooooooon the Electron version of Git-it will be ready and I'll be phasing this one out, so I'm going through and porting issues and closing out ones that won't be applicable in the new version. This one is the later, woot!
