### ISSUE TITLE
Install WARN for node versioning

### ISSUE THREAD

**Issue by Gregory-Phillips** [jlord/git-it#130]
Just figured this tut couldn't hurt to have a good refresh corse.

In the install I saw this warn:

npm WARN engine github-oauth@0.0.4: wanted: {"node":"v0.8.x"} (current: {"node":"0.10.31","npm":"1.4.26"})

I have set up a new 2014 computer so I ran fresh installs of everything.

**Comment by jlord** [comment]
In the new version of [Git-it](https://github.com/jlord/git-it-electron) Node will be bundled with the app so we won't have to worry, woot! Thanks!
