### ISSUE TITLE
Final step in Merge Tada! not verifying

### ISSUE THREAD

**Issue by benji1304** [jlord/git-it#138]
Sorry - i logged this issue on jlord/patchwork - I think it should have been here? 

----
I've been going through each step, all going fine until i get to the very last step to verify the final part and I have the following

ACTUAL EXPECTED

"Branch has been merged!" "Branch has been merged!"
"Uh oh, branch is still there." != "Branch deleted!"
"" ""

FAIL

I can't find the branch that hasn't been deleted?

**Comment by jlord** [comment]
Hmm. Just to be clear, when you run `git branch` inside of `patchwork` it does not list `add-benji1304`?
