### ISSUE TITLE
Githubbin problem

### ISSUE THREAD

**Issue by dcooper2** [jlord/git-it#141]
What do you do when you run the command to add your username but when you verify, the actual results are:
ACTUAL                                          EXPECTED
------                                                --------
"Username added to Git config!"(green)        "Username added to Git config!"(green)
"GitHub account matching Git config"(red)   != "You're on GitHub!"       (red)     
"username wasn't found."(red)                     != "Username same on GitHub and"  (red)
""                                                           != "Git config!"              (red)    
# FAIL            

Everything was spelled correctly and the cases were correct.

**Comment by nathan-j-brenner** [comment]
I'm getting the same message.  Did you ever figure it out?

**Comment by jlord** [comment]
Just left a comment on your issue @nathan-j-brenner, hopefully that helps out! 

@dcooper2 Hmmm, to help me figure out what might be going on could you run these commands in your terminal and tell me what they output?

```bash
$ git config user.email
$ git config user.name
$ git config user.username
```

**Comment by hicksca** [comment]
I just submitted a possiable fix to this if I'm understanding the issue correctly. https://github.com/jlord/git-it/pull/190  
It allowed me to use `user.name` or `user.username` in my .gitconfig without repercussions. I think as it is today the verification is only done against `user.username` so if you have `user.name` it fails.

**Comment by jlord** [comment]
Closing this issue because haven't gotten a response, but if you feel you have a similar issue make sure that you have the **3** properties below set in your config.

These commands will return for you what you have stored:

```bash
# your email address "octocat@github.com"
$ git config user.email
# your full name "Mona Lisa Octocat"
$ git config user.name
# your GitHub username "octocat"
$ git config user.username
```

:pizza:

**Comment by seobrat** [comment]
Can't thank you enough....

**Comment by AlexTes** [comment]
I'll try and finish my walkthrough of `git-it` today and see if I can PR this issue away. 😄 .

**Comment by AlexTes** [comment]
#236 is supposed to fix this. 
Sadly I still don't have the time to more actively help out.
