### ISSUE TITLE
git-it server does not work on windows

### ISSUE THREAD

**Issue by zonplm** [jlord/git-it#142]
I guess git-it does not work in cmd window

C:\Users\tpm-dev>git-it server
Open this in your browser: http://localhost:56297

I got this message:

File not found. :(

I got the same message in git bash too.

**Comment by hardik-potenza** [comment]
I am also facing same issue.

**Comment by hardik-potenza** [comment]
Hi,

I also ran into same error. But after chatting on gitter with @mydigitalself. He suggested to install it globally instead of locally. 

command for it : 

 npm install -g git-it

**Comment by jlord** [comment]
Yes, you **must** install it globally as @hardik-potenza mentioned :point_up: 

@zonplm with Windows I recommend using Git Shell (see [readme](https://github.com/jlord/git-it#what-youll-need-to-run-git-it)). I cannot speak to what happens in cmd or git bash. 

So, using Git Shell, run ```npm install -g git-it``` confirm a global install, then run ```git-it```. Let me know how it goes!
