### ISSUE TITLE
Using with custom remote server

### ISSUE THREAD

**Issue by DaAwesomeP** [jlord/git-it#144]
I am running a GItLab server and I need to teach people git. I really like git-it. Is it possible to use my own remote git server instead of GitHub?

**Comment by jlord** [comment]
It is _possible_. 

You'd need to set up your own bot, basically fork (or re-write) jlord/reporobot and wire it up to work with whatever Git API and repositories you want to use (right now it uses the GitHub API and jlord/patchwork as the base repo). You'd then need to fork Git-it to send requests to your server.
