### ISSUE TITLE
git-it terminal menu crashes/quits

### ISSUE THREAD

**Issue by enerve** [jlord/git-it#146]
I installed nodejs, git, git-it, etc.
I run "git-it" and select any menu item and hit ENTER. The program seems to quit immediately, for example:

  #####################################################################
  ##                         ~~  GET GIT  ~~                         ##
  #####################################################################

  Install Git on your computer and configure your name and email.

  --------------------------------------------------------------------
 » To launch the guide, run: `git-it server`.
 » Or copy this address to your browser:
 » /usr/local/lib/node_modules/git-it/guide/index.html 
 » To verify your work for this problem, run: `git-it verify`.
 » For help with this problem or with git-it, run:
   `git-it help`.

.....$ 

I'm on Mac OS X 10.10, latest version of GitHub, git, nodejs, etc.

**Comment by enerve** [comment]
git-server seems to work fine on localhost

**Comment by jlord** [comment]
Would you mind re-installing git-it and seeing if you get the latest footer on the challenges?

```bash
npm install -g git-it
```

**Comment by enerve** [comment]
Yeah I see the latest footer. Closing...
