### ISSUE TITLE
git-it verify fails for first challenge (Get Git)

### ISSUE THREAD

**Issue by dougaitken** [jlord/git-it#147]
![gititone](https://cloud.githubusercontent.com/assets/52214/6405396/e10faef6-be1a-11e4-99df-f6e6d5cce628.jpg)

So I followed the instructions and it failed, should we be doing ```git-it verify``` at this stage?

**Comment by jlord** [comment]
From the screen shot it looks like you are actually not on the first challenge—it says that it is verifying 'Repository'. 

Try running `git-it` again to launch the menu and selecting the very first challenge and then try `git-it verify` again.

**Comment by dougaitken** [comment]
Ah...that is what happened! Thanks @jlord
