### ISSUE TITLE
The Challenge of Repositories, the file verify should take care of the system's language setting.

### ISSUE THREAD

**Issue by hygkui** [jlord/git-it#148]
in my os the env i set as :
> LANG=zh_CN.UTF-8

so when run `git status`, it returns
> 位于分支 master

> ...

not the expect:

> On branch master

> ...

so the verify.js ( *problems/repository/verify.js* ) should take care
of the git language.

**Comment by bwilles** [comment]
Hope you push it soon to npm. Comes in a little disturbing, especially as the first verifies ok also in other language. In any case: Thanks for fixing it :)

    $ export LANG=en_EN.UTF-8
    $ git-it verify
    Verifying "COMMIT TO IT"...

    ACTUAL                             EXPECTED
    ------                             --------
    "Changes have been committed!"     "Changes have been committed!" 
    ""                                 ""                             
    # PASS

    Your solution to COMMIT TO IT passed!
    -----------------------------------------------------------------

    You have 9 challenges left.
    Type `git-it` to show the menu.

    -----------------------------------------------------------------

    $ export LANG=de_DE.UTF-8
    $ git-it verify
    Verifying "COMMIT TO IT"...

    ACTUAL                             EXPECTED
    ------                             --------
    "Hmm, can't find"               != "Changes have been committed!" 
    "committed changes."            != ""                             
    ""                              != null                           
    # FAIL

    Your solution to COMMIT TO IT didn't match the expected output.
    Try again!
    -----------------------------------------------------------------

    $

**Comment by jlord** [comment]
Sorry about that! Don't know how I forgot to actually publish it :grin: but I've just done so. Git-it `1.6.4` has the language update :+1: Thanks!!
