### ISSUE TITLE
Not sure what to branch on Branches Aren't Just For Birds

### ISSUE THREAD

**Issue by zg** [jlord/git-it#150]
There's no indication of what repository I should be branching, instead the workshop goes on saying:

>Type git status to see what branch you're currently on (it should be 'gh-pages').

**Comment by loudmouthts** [comment]
I'm going to be one of the best to use GitHub now you watch me and see.

**Comment by loudmouthts** [comment]
with your help of course I'm going to worry you guy's so much until I become a professor of
GitHub and then you will see what I'm really capable of witch is getting people's attention and keeping
it until I won't to give it back. I'm still the loudmouth Tommy Virdell I will not be shut up.

**Comment by zg** [comment]
What are you talking about?

**Comment by jlord** [comment]
:wave: @zg!

You're working on your fork of `Patchwork` throughout the Git-it challenges. I sometimes just refer to it as 'your fork' as in the challenge statement:

> Create a new branch on your fork for your contribution.

In this challenge you're branching _from_ the `gh-pages` branch and creating a new branch for your edits.

**Comment by zg** [comment]
I figured as much when I was doing the challenge, but it didn't seem obvious from the text. :grin:

**Comment by loudmouthts** [comment]
join the club my friend but I stayed up all night reading and I feel a
little bit smarter this morning Oh yes I dooooo.


Kiss&Tell:loudmouthTommy Virdell

**Comment by jlord** [comment]
@zg I'm always up for improving the text and feel free to submit a pull request if you have ideas for that part :sparkles:
