### ISSUE TITLE
Fail at first challenge (GET GIT)

### ISSUE THREAD

**Issue by wpuser2014bis** [jlord/git-it#152]
Hi i 'm following the git it guide and i am failing at the very first challenge (Get Git Install and configure Git).
I went through all the steps in the guide,  I am able to verfiy that Git is there by typing $ git --version and retrieving the version (which is: 1.9.5.github.0; by the way i am not adding the dollar sign when i type the commands so that is not the mistake).
But when I type my username and mail and run the verifty command this is what I get:
ACTUAL                             EXPECTED
------                             --------
""                              != "Email Added!"
null                            != "Found Git installed."
null                            != ""
# FAIL

Your solution to GET GIT didn't match the expected output.
Try again!
-----------------------------------------------------------------

This are the commands exactly as i wrote them (I replaced my username and mail, though):

git config --global user.name "username"
git config --global user.username gitusername
git config --global user.email mymail@example.com

I have tried this numerous times and had no success. What am I doing worng?

Thank you very much for your answers.

**Comment by P1xt** [comment]
git config --global user.name "username"
git config --global user.email "mymail@example.com"

is what worked for me.

Note that both the name and email must be enclosed in quotes. If you try both of them with double-quotes and that doesn't work, try replacing the quotes with single quotes. I seem to recall someone mentioning that on Windows, you have to use single quotes.

**Comment by jlord** [comment]
> Note that both the name and email must be enclosed in quotes
> I seem to recall someone mentioning that on Windows, you have to use single quotes.

Oh, this will be good to verify. I see I don't have it in quotes in the Guide so I can make that change. Thanks @P1xt!

Let me know if this works @wpuser2014bis.

**Comment by PokimLee** [comment]
I just meet the problem as same as @wpuser2014bis 

After I type this in the terminal:
$ git config --global user.email <1325147857@qq.com>

I received the below message:
-bash: syntax error near unexpected token `newline'

what should I do now?

**Comment by P1xt** [comment]
Try putting quotes around your email like:
$ git config --global user.email "1325147857@qq.com"

**Comment by jlord** [comment]
Eek, sorry for the delay on this fix! I just pushed an update to the guide that uses quotes around the email. :balloon:

**Comment by PokimLee** [comment]
@P1xt  Yes! It woooooorks! thank you!

**Comment by P1xt** [comment]
@Pokin Awesome:)
