### ISSUE TITLE
Emphasize HTTP over SSH in Challenge 5 Remote Control

### ISSUE THREAD

**Issue by patwashburn** [jlord/git-it#158]
I love this guide! On Activity 5 (Remote Control), I ran into the "Permission denied (publickey)" error and had to poke around the Github site to resolve the situation before I could complete the activity. It might be helpful to add a link to https://help.github.com/articles/error-permission-denied-publickey/ for others who run into the same situation.

**Comment by jlord** [comment]
Hi @patwashburn! I'm so glad you like the guide! It seems like you were using the SSH url for your repository rather than the HTTP one. 

The guide mentions selecting HTTP, but I think I can edit it to make that clearer :+1: 

Thanks!
