### ISSUE TITLE
git-it guide is linux-centric

### ISSUE THREAD

**Issue by pgorbas** [jlord/git-it#159]
The git-it guide examples are all written assuming a linux OS, but some users will be using windows DOS.

**Comment by jlord** [comment]
In places where I was aware of commands that differed I've included the applicable Windows snippet. As a Linux based OS user myself, however, I'm limited in what I know about on another OS.

But!—If you're a Windows user and know of places where this can be improved, your pull requests would be greatly welcomed :smile: I definitely want the guide to be relevant for as many people as possible, but I don't know what I don't know :balloon: 

Here's the [section of the contributing doc on the Guide](https://github.com/jlord/git-it/blob/master/CONTRIBUTING.md#the-guide). Even an issue with a list of Guide places and then a suggestion would be helpful.

Thanks!
