### ISSUE TITLE
Stuck in Exercise2-Repository

### ISSUE THREAD

**Issue by AxisWhistle** [jlord/git-it#162]
I did as the instructions of chapter Repository, but it just does not work when I run git-it verify.
What i did is as follows:
![image](https://cloud.githubusercontent.com/assets/7236630/6996291/5afa50b8-dbb2-11e4-8a9e-2be62d5770ba.png)

The platform i use is Ubuntu 14.04, and the node version is v0.10.37, the npm version is 2.7.4 and i installed git-it workshop by npm globally.

Enlish is not my mother tongue, please pardon my mistake about English.

**Comment by jlord** [comment]
Hi @AxisWhistle! 

So does your Git use Chinese as its language? It may be that that is why this is failing. Git-it checks against English Git output....though I thought that had actually be changed recently. I will look into it.

**Comment by jlord** [comment]
Ok, looks like that change have Git-it use English did come in [here](https://github.com/jlord/git-it/commit/bb052d029100633133d3fcc3cbf15ecc5d9cc19d) but I forgot to publish that update :flushed: 

I've just published it so Git-it is now at version `1.6.4`. You should update your version of Git-it and try again. Your current progress will be saved.

Install latest:

```bash
$ npm install -g git-it@1.6.4
```

**Comment by AxisWhistle** [comment]
Sorry to reply you so late @jlord 
I learned git and github using their official documentation later and did not follow the git-it workshop.
But I still appreciate your effort.
Just being polite, I tried your solution out and failed again though I may not need the solution now that I had achieved my goal by another way.
Still thanks a lot.
