### ISSUE TITLE
last git-it verify won't pass for Merge Tada

### ISSUE THREAD

**Issue by danraley** [jlord/git-it#165]
I verified my branch was merged however when I run git-it verify I receive the following error;
danraley@nodeschool:~/workspace/patchwork (gh-pages) $ git-it verify
Verifying "MERGE TADA!"...

ACTUAL                             EXPECTED
------                             --------
"Branch has been merged!"          "Branch has been merged!"      
"Uh oh, branch is still there." != "Branch deleted!"              
""                                 ""                             
# FAIL

**Comment by mallegrini** [comment]
Same here. And I deleted my branch (add-mallegrini) on my fork on github.

**Comment by jlord** [comment]
Did you delete them locally? When you run `git branch` do they show up?
