### ISSUE TITLE
Creating an executable which will not require NodeJS

### ISSUE THREAD

**Issue by IonicaBizau** [jlord/git-it#166]
I recently saw the [`enclose` project](https://github.com/igorklopov/enclose) which seems to be awesome. It compiles NodeJS code into executables which not require NodeJS to be installed on the computer.

If we can provide such an executable the users will not need to [install NodeJS on their machines](https://github.com/jlord/git-it#what-youll-need-to-run-git-it).

If that works like a plan, let me know if I must give a try. :smile: 
Currently `enclose git-it.js` outputs some errors, but I guess they should be simple to fix via a PR.

**Comment by jlord** [comment]
Woot we have Git-it Electron now (which you know :smile:) so I think we can close this here :+1:  Thanks!

**Comment by IonicaBizau** [comment]
@jlord Oh, yeah! :joy:
