### ISSUE TITLE
Failed to push changes to branch in Branches Aren't Just for Birds

### ISSUE THREAD

**Issue by sodium** [jlord/git-it#168]
I have added my text file add-sodium.txt to contributors/ and it is committed, but I got Permission denied when I try to push it to my branch.

bash-3.2# git push origin add-sodium
remote: Permission to jlord/patchwork.git denied to sodium.
fatal: unable to access 'https://github.com/jlord/patchwork.git/': The requested URL returned error: 403

**Comment by sodium** [comment]
Solved

**Comment by jlord** [comment]
:tada:
