### ISSUE TITLE
repository section not working

### ISSUE THREAD

**Issue by julianomqs** [jlord/git-it#175]
I followed up repository section, but `git-it verify` is not verifying.
It is saying:
`This folder isn't tracked by Git.`

But `git status` says otherwise:
`In master branch`
`Initial submit`
`nothing to send (create/copy files and use "git add" to register)`

My OS is Ubuntu 14.04 LTS
Git version is 2.4.1

P.S.: I completed `GET GIT` workshop.

Thank you.

**Comment by jlord** [comment]
Interesting, your Git seems to have different output than normal. The verify script expects the first line to be "On branch" and then the branch, not "In master branch" as you've written above. 

Am wondering what else might be different about your Git?

**Comment by jlord** [comment]
I've just upgraded my own Git and now have version 2.4.3. I still get the same (expected) output:

```bash
On branch gh-pages
Your branch is up-to-date with 'origin/gh-pages'.
nothing to commit, working directory clean
```

Where did you download your Git from and have you added anything that might have changed the default behavior?

**Comment by julianomqs** [comment]
Locale problems :(
Sorry for the incovenience.
