### ISSUE TITLE
IT'S A SMALL WOLRD ... fail because connection refused, why ?

### ISSUE THREAD

**Issue by ghost** [jlord/git-it#176]
Hi,

I have completed all previous steps in GIT-IT and I don't understand why IT'S A SMALL WORLD fails because of a connection error.

I have added the contributors as requested but when I run the git-it verify I have the following error

"{ [Error: connect ECONNREFUSED]" != "Reporobot has been added!"    
"  code: 'ECONNREFUSED',"       != ""                             
"  errno: 'ECONNREFUSED',"      != null                           
"  syscall: 'connect' }"        != null                           
""                              != null                           
# FAIL

What should I do ?

Thanks in advance for your answers.

**Comment by jlord** [comment]
Are you online when running this? When this test runs it makes a request to GitHub to see if @reporobot has been added and looks like it's not able to make that request for some reason.

**Comment by Yellowmat** [comment]
I am online and able to verify some tests.
I may have a proxy problem, I have to check that.

**Comment by jlord** [comment]
Were you able to get through the challenge?

**Comment by theharshitgarg** [comment]
Verifying "IT'S A SMALL WORLD"...

ACTUAL                             EXPECTED
------                             --------
""                              != "Reporobot has been added!"    
# FAIL

Your solution to IT'S A SMALL WORLD didn't match the expected output.
Try again!

**Comment by jlord** [comment]
Closing, hopefully we can see what kind of connection errors are coming in through the pull request :point_up:
