### ISSUE TITLE
Stuck on Remote Control challange

### ISSUE THREAD

**Issue by killawabbit** [jlord/git-it#182]
Hello! I'm getting the following error when trying to verify the challange:

"No evidence of push."

I've followed the guide as straight as possible and even did an extra push, but no change. What can be wrong?

**Comment by jlord** [comment]
Hi!

What happens when you run `git reflog show origin/master`, this is what that challenge is running.

**Comment by killawabbit** [comment]
Error message

fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by killawabbit** [comment]
should I've put in the respective paths for 'origin' and 'master' myself or should they've been set as values somewhere?

**Comment by jlord** [comment]
Hmm. Your remote named `origin` should be pointing to your fork of Patchwork. Let's double check that, can you run:

```
$ git remote -v
```

**Comment by killawabbit** [comment]
The command gives this response:

origin	https://github.com/killawabbit/patchwork.git (fetch)
origin	https://github.com/killawabbit/patchwork.git (push)
upstream	https://github.com/jlord/patchwork.git (fetch)
upstream	https://github.com/jlord/patchwork.git (push)

**Comment by jlord** [comment]
Kewl, thanks for checking that! I just realized that on the Remote challenge, the Patchwork repository hasn't been introduced yet, you're still working with your `hello-world` repo (sorry about that confusion, was just answering a question about the other).

So you'll need to go back inside that repository you created in the Repository challenge. Depending on where you put things you may have to move around a bit, or you may be able to back out of the `patchwork` directory and into `hello-world`:

```
$ cd ..
$ cd ../hello-world
```

You should run the verify step for this challenge from inside of `hello-world`.

**Comment by killawabbit** [comment]
Ok, a bit confused, yes. But going into the hello-world repo and verifying worked perfect - as I knew it should ;-)

**Comment by jlord** [comment]
Awesome! :sparkles:
