### ISSUE TITLE
Stuck in challenge "Repository"

### ISSUE THREAD

**Issue by Silerra** [jlord/git-it#185]
What am I doing wrong here?
![bildschirmfoto4](https://cloud.githubusercontent.com/assets/7958950/8398914/87c64614-1e02-11e5-90b0-3654182f4a13.png)

I hope someone can help me.

Greetings

**Comment by jlord** [comment]
It looks like your Git doesn't use English, which is what Git-it uses to see if responses are what it expects. I thought that we had a fix for this, though so I will check up on it!

**Comment by jlord** [comment]
So it should have been fixed with https://github.com/jlord/git-it/pull/149 which would have made it so that when Git-it is verifying it's changing the language to English. I'm not quite sure why it's not working.

**Comment by Silerra** [comment]
Because probably doesn't exists the english lang-pack. Then load automatically the language from OS config.

**Comment by jlord** [comment]
@Silerra thanks for opening this issue so that we could get to the bottom of this! :sparkles:
