### ISSUE TITLE
REPOSITORY challenge not working correctly

### ISSUE THREAD

**Issue by aepedraza** [jlord/git-it#189]
Hi, I've just completed the git-it workshop but in the second lesson I created the `hello-world` repository by writing in the console:
```
# mkdir hello-world
# cd hello-world
/hello-world# git init
```
But when I submit with `git-it verify` it gives me a FAIL answer ¿what can be wrong?
Thanks in advance

**Comment by jlord** [comment]
I'm not sure if you've typed the commands incorrectly above or if it is accurate to what you typed but you should be doing:

```bash
# create new directory
$ mkdir hello-world
# go into that directory
$ cd hello-world
# initialize
$ git init
```

Are these the steps you took? If so did you get an error message after running `git init` inside of `hello-world` ?

**Comment by aepedraza** [comment]
indeed, those are the steps I took. `git init` didn't gave me an error, when I submit my answer via `git-it verify` for that point, gives me a FAIL answer, as if I was wrong, is it understood?
I'll try later to submit some screenshots, so it gets clearer...

**Comment by jlord** [comment]
Hmm, the next thing to try is, inside of `hello-world` run this command: `git status` that is what Git-it is running to determine if it has been initialized as a Git repository.

**Comment by aepedraza** [comment]
the `git status` command gives me the following result:

```
En la rama master
Commit inicial
nada que hacer (crear/copiar archivos y utilice «git add» para continuar)
```

I have a spanish version of git, translated is:

```
On branch master
Initial commit
nothing to do (create/copy files and use «git add» to continue)
```

**Comment by jlord** [comment]
Ah, Git-it only worked with English though a fix should be in now for that.

If you re-install `npm install -g git-it` it should give you version `1.6.9` and hopefully that works.

**Comment by JorsiRamos** [comment]
I'm having the same issue. I follow these three steps too, the git status output is:
`On branch master
Initial commit
nothing to do (create/copy files and use «git add» to continue`

But when I tried to verify, the output is this message:
`ACTUAL                             EXPECTED
------                             --------
"This folder isn't "            != "This is a Git repository!"    
"being tracked by Git."         != ""                             
# FAIL`

Im using the english version of git.

**Comment by JorsiRamos** [comment]
I'm having the same issue and I'm using the english version of git. I follow these three steps too, the `git status` output is:
`On branch master Initial commit nothing to do (create/copy files and use «git add» to continue`
But when I tried to verify, the output is this message:
`"This folder isn't being tracked by Git."`
