### ISSUE TITLE
"Get git" section: no access to git commands in CMD after installing GitHub.

### ISSUE THREAD

**Issue by MyPCIsBetter** [jlord/git-it#191]
Tutorial says, that after installing GitHub I will have also installed git. But in Windows CMD there are no git commands available.

**Comment by jlord** [comment]
Hi! In the Readme I suggest [using Git Shell](https://github.com/jlord/git-it#what-youll-need-to-run-git-it) for the console on Windows. You should have it on your computer after you've installed the GitHub desktop app.

**Comment by jlord** [comment]
Hope you had luck with Git Shell, CMD usually won't work.
