### ISSUE TITLE
learning remote control

### ISSUE THREAD

**Issue by Hans-Park** [jlord/git-it#193]
Dear Sirs,

I am learning Remote Control.

I try to send my branch named  'master' to my remote on GitHub named 'hello-world' ,but
nothing happened. I input like:

   $ git push hello-world master. 

'hello-world' is my remote repository.

How can I overcome this issue?

Your help will be very appreciated.

**Comment by jlord** [comment]
Hi!

In the challenge you set the name of the remote to `origin`. Your branch name is `master` and your project name is `hello-world`. So what you should be running is:

```bash
# to go into your hello-world folder
$ cd hello-world
# push changes from your master branch to your remote, origin
$ git push origin master
```

**Comment by Hans-Park** [comment]
I tried  as your instruction, but failed.
The answers are like this:

cd hello-world: No such file or directory
git push origin master: fatal:repository 'https:github.com/'not found

even I made local git, remote git, text file.

Your help will be very appreciated.
Thanks

**Comment by Hans-Park** [comment]
I mean I made a local repository  and a remote repository.

**Comment by jlord** [comment]
If there is no `hello-world` directory then I think it may be best to go back to the second challenge where you create it because you should have created it and need it.

**Comment by Hans-Park** [comment]
Thank you very much.

Another question:

I like to change my username Hans-Park  into phans. How can I do that? 
I think The hyphen(Hans-Park) may cause problems.

**Comment by jlord** [comment]
@Hans-Park here's the article that will help you with that: https://help.github.com/articles/changing-your-github-username/

**Comment by Hans-Park** [comment]
Thank you very much.

I 'd like to delete some of my repositories to review GitHub again from the first.
How to delete them?

I am very sorry to bother you with so many asking.
Thank you.

**Comment by Hans-Park** [comment]
Thank you.

Everything is OK.

**Comment by jlord** [comment]
Ok, great to hear!

**Comment by Hans-Park** [comment]
Dear jlord,

I tried to delete my old username  'Hans-Park' , but failed.

As you see, I have two username : phans(new one),  and Hans-Park(old one)

How can I take out  this old diablo to the Andromeda?

**Comment by jlord** [comment]
You should be able to delete the account through the settings page for that account. I think it would be best if you email [support@github.com](mailto:support@github.com) as they would surely know exactly what to do :sparkles:
