### ISSUE TITLE
asking help

### ISSUE THREAD

**Issue by Hans-Park** [jlord/git-it#194]
I am sorry.
I have return to this site after long time absence.

I forgot my username and password for using GitHub.
How can I recover them?

My previous username and password do not work.

Thank you.

**Comment by jlord** [comment]
You can try to reset using your email: https://github.com/password_reset and if that doesn't work the folks at support@github.com should be able to help you out. Good luck!

**Comment by Hans-Park** [comment]
I got it. Thank you so much.

**Comment by jlord** [comment]
:sparkles:
