### ISSUE TITLE
about Remote Control

### ISSUE THREAD

**Issue by chyny** [jlord/git-it#198]
Hi!

I am learning Remote Control.

To the instructions, I did:

$ git remote set-url origin https://github.com/chyny /hello-world

,but the result is as follows.

No evidence of push             ! = "Bingo! Detected a push."
#  FAIL 

How can I overcome this issue?
Waiting for your help.

Thank you.

**Comment by chyny** [comment]
Hi!
Thank you so much.
I passed Remote Control thanks to your help!

Another question:

In case of private repository, it charges $ 7.00/a Month. 
What's the difference between a public repository and a private repository?

There are any benefits or merits from a private repository ?

And,

I want to learn PIXI.js Engine to make animations someday in the future.
Do you have any idea what is the most  effective way to learn  PIXI.js engine?

Your recommendation will be very appreciated.

Thank you.

**Comment by jlord** [comment]
Awesome!

> What's the difference between a public repository and a private repository?

A public one is one that is accessible to anyone—like this one for Git-it. A private repository is only accessible to you and those you specifically add as collaborators. The private repository cannot be found by someone who hasn't been added to it and it won't be listed anywhere as even existing except to you and those you've added to it. 

There are any benefits or merits from a private repository ?

It's totally up to you and your needs. If you need your repository to be hidden then it makes sense. If you don't then you don't :)

> Do you have any idea what is the most effective way to learn PIXI.js engine?

Sorry, I don't know anything about it. 

I'm glad you passed the challenge! :tada:

**Comment by chyny** [comment]
Thank you so much.

It is very kind of you.

Thank you again.

**Comment by chyny** [comment]
Hi!

I am learning  "Branch are not just for birds" .

By the instruction, I did:

1. git status
2. git branch add-chyny(my username)
3. git checkout add-chyny
4. add-chyny.txt //creating a new file and saving it in

            patchwork/contributors/add-chyny.txt

5. check-in:
    1) git status
    2) git add add-chyny.txt
    3) git git commit -m "comment"
    4) git push origin add-chyny.txt

6. git-it verify. The result is :      

           FAIL
 What is the wrong I did?

**Comment by chyny** [comment]
Another result is :

     Username for 'https://github.com': chyny
     Password for 'https://chyny@github.com':
    error: src refspec add-chyny.txt does not match any.
   error: failed to push some refs to 'https://github.com/chyny/hello-world.git'

Thanks.

**Comment by chyny** [comment]
Hi!

Now I am on "It's a small world".

By the instruction, I input my username, then clicking "Add collaboration".
The URL is :          

            GitHub, Inc.[US] https://github.com/chyny/patchwork/settings/collaboration

but the result is FAIL.

 What is my wrong doing?

Thank you.

**Comment by jlord** [comment]
> By the instruction, I input my username

You should be adding @reporobot as a collaborator, and therefore it's username and not yours. Hope that helps!
