### ISSUE TITLE
It's A Small World

### ISSUE THREAD

**Issue by 16aces** [jlord/git-it#199]
I added Reporobot specified. I ran git-it verify, it says Reporobot has not been added. Those are the only steps listed I have no idea what I'm supposed to do.

**Comment by jlord** [comment]
Hmm, you're right, @reporobot has been added to your fork. The check for this is pretty simple, it returns either true or false so I'm not sure what could be causing it to be wrong. Have you tried again?

**Comment by 16aces** [comment]
just checked again still not working

**Comment by jlord** [comment]
I haven't seen this issue come up before and when I use @reporobot's API to see what it returns at the added-as-collaborator status I get:

```json
{
  "collab": true
}
```

And `git-it` should use that to return a pass:

```js
if (body.collab = true) console.log("Reporobot has been added!")
```

Unfortunately I don't have any idea what might be going wrong. Just to confirm again, it's telling you "Reporobot doesn't have access to the fork"?

**Comment by jlord** [comment]
Actually—can you confirm that in Git you set your `username` as `16aces` because when I set my username to that on my computer, it passes:

![screen shot 2015-09-21 at 11 55 36 am](https://cloud.githubusercontent.com/assets/1305617/10001679/c8b6f4f6-6057-11e5-9e71-41a44e6d3342.png)

To confirm what your username is set to, type:

```
$ git config user.username
```

**Comment by 16aces** [comment]
Changing the user name did it, Thank you very much.

**Comment by jlord** [comment]
Yay! :tada:

**Comment by phpdeveloperbalaji** [comment]
It didn't work for me too, even after changing the username to 16aces.
