### ISSUE TITLE
Different link for node.js install?

### ISSUE THREAD

**Issue by jordanmunson** [jlord/git-it#203]
I noticed that in README.md that the node.js download link points here: `https://nodejs.org/download/` -- that ends up looking like:
<img width="709" alt="screen shot 2015-10-14 at 7 15 51 pm" src="https://cloud.githubusercontent.com/assets/1873867/10500668/03baed7a-72a8-11e5-878f-4fbffa84bce6.png">

I'd recommend swapping that link for `https://nodejs.org/en/download/`instead, as it looks a touch nicer to someone new at git:

<img width="1198" alt="screen shot 2015-10-14 at 7 16 43 pm" src="https://cloud.githubusercontent.com/assets/1873867/10500686/21f542d6-72a8-11e5-91fd-10482368d9be.png">

**Comment by jlord** [comment]
Ah, yeah they did update their website recently. Thanks for the heads up!
