### ISSUE TITLE
Git Hubbin not accepting user name

### ISSUE THREAD

**Issue by QdelBastardo** [jlord/git-it#206]
using git-it with c9.io. logged in to c9.io with github account that i had created some time ago.  In trying to do the git-hubbin exercise, it will not accept my username, regardless of the case that i use.
My github account name is "QdelBastardo".  the c9.io terminal prompt shows 'qdelbastardo'.  i have tried both and neither one works.

I have tried;
git config --global user.name "QdelBastardo"
git config --global user.name QdelBastardo
git config --global user.name "qdelbastardo"
git config --global user.name qdelbastardo

they all verify in the config, just not in the exercise.

[https://github.com/QdelBastardo](https://github.com/QdelBastardo)
[pics](http://imgur.com/a/MYrsF)

**Comment by jlord** [comment]
I don't know anything about c9.io and so I don't know why it would force your global git config to be lowercase. If it does in fact force it to be lowercase then this challenge will fail because GitHub is case sensitive with usernames.

Is it possible for you to use Git-it without c9?

**Comment by QdelBastardo** [comment]
Thank you.  I will open an issue with c9.io then.

**Comment by cristianvnica** [comment]
Hi, I had the same problem today :) 

The issue is that we wrote: 
`git config --global user.name QdelBastardo` 
instead of: 
`git config --global user.username QdelBastardo`

Have a nice day everybody!
