### ISSUE TITLE
Trying to push a branch

### ISSUE THREAD

**Issue by TheBisonGuy** [jlord/git-it#208]
I am trying to push the branch but it says that permission to jlord/patchwork.git is denied to my username. I can't finish the challenge if it doesn't go through and I can't figure out what I am doing wrong

**Comment by wordyallen** [comment]
+1

**Comment by wordyallen** [comment]
@TheBisonGuy  Try doing the final push on your own repo. I was thinking we had to merge back too.

**Comment by jlord** [comment]
You should be doing the push to _your_ repository and _not_ `jlord/patchwork`. 

You push your branch to your repository (your fork of `patchwork`), you'll then make a pull request to `jlord/patchwork` for the changes in your fork.

You can check what locations you can push to by checking your remotes: `git remote -v`. You should have one set to `jlord/patchwork` in which to _pull_ changes from and one set to your fork in which to _push_ your changes too. 

Good luck!
