### ISSUE TITLE
During install I received 3 warnings: 1 engine warning, and 2 deprecated warnings.

### ISSUE THREAD

**Issue by johan718** [jlord/git-it#211]
It would be nice not to get these warnings during install:
```
WARN engine github-oauth@0.0.4: wanted: {"node":"v0.8.x"} (current: {"node":"4.2 
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```
Just giving you a heads-up for, what it's worth.

**Comment by jlord** [comment]
Thanks! I'll soon be releasing the first version of Git-it as a desktop app and these types of warnings won't show so I'm going to close this one here.
