### ISSUE TITLE
Requesting You Pull Please exercise not clear/working.

### ISSUE THREAD

**Issue by Philosophist** [jlord/git-it#217]
The Requesting You Pull Please exercise is either unclear or out of date. Possibly both. When I try to make a pull request, nothing shows up with my add-username (add-Philosophist) to make it easy and everything I've managed to compare shows me an error for the two being identical. I can't figure out how to specify the original from another repository and the syntax for the add-Philosophist is only recognized as existing with the syntax @{add-Philosophist}. I've tried combinations of pull requests comparing anything I can think of as a remote or branch on both my repository and the original. If nothing else, the instructions need to be more clear.

**Comment by jlord** [comment]
I'm not sure exactly what you're describing above but here is the comparison between your branch on your fork with the original branch on the original repository: https://github.com/jlord/patchwork/compare/gh-pages...Philosophist:add-Philosophist?expand=1

I got there by:

- Going to your fork: https://github.com/Philosophist/patchwork
- Selecting your branch: https://github.com/Philosophist/patchwork/tree/add-Philosophist
- Clicking new Pull Request: https://github.com/jlord/patchwork/compare/gh-pages...Philosophist:add-Philosophist?expand=1

<img width="360" alt="screen shot 2016-01-21 at 3 06 51 pm" src="https://cloud.githubusercontent.com/assets/1305617/12496070/a0fda4ec-c050-11e5-8ecd-a7c4e7c850b5.png">

I'm currently re-working all of Git-it as a new desktop app and will review the instructions on this page. Thanks!
