### ISSUE TITLE
Ambiguous wording in Forks And Clones

### ISSUE THREAD

**Issue by DCtheTall** [jlord/git-it#237]
Hey all,

Current output for the problem:

```
 #####################################################################
  ##                    ~~  FORKS AND CLONES  ~~                     ##
  #####################################################################

  Fork a project from GitHub.com and clone it locally.
  
  Use the guide (see below) for step-by-step instructions.

  ---------------------------------------------------------------------

  » To verify your work for this problem, run: `git-it verify`.
  » Run `git-it` again to launch menu & go onto next challenge

  GUIDE

  » Open the guide in your browser: jlord.github.io/git-it
  » Traditional Chinese guide: jlord.github.io/git-it/index-zhtw.html

  » To view guide offline, copy this address to your browser:
  » /home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/git-it/guide/index.html 
  » /home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/git-it/guide/index-zhtw.html
```

The problem asks for you to clone a project on Github, however the test condition in verify.js is:

`show.match("upstream") && show.match("github.com[\:\/]jlord/")`

Nowhere in the problem does it speficy that we should clone a project that belongs to jlord.

Thanks!

**Comment by jlord** [comment]
Hiya!

The terminal output (above) pairs with a web-based guide. The page for this challenge suggests specifically a project to fork: http://jlord.us/git-it/challenges/forks_and_clones.html.

<img width="429" alt="screen shot 2017-04-25 at 2 17 34 pm" src="https://cloud.githubusercontent.com/assets/1305617/25400879/f3485d24-29c1-11e7-9d71-88a4c5384d9e.png">

---

I'd recommend checking out the desktop app version of Git-it which is more update to date and has all of the guide content in one place, reserving the terminal for regular typical use.

https://github.com/jlord/git-it-electron
