### ISSUE TITLE
http://githubusername.github.io/repositoryname  format is out of dated

### ISSUE THREAD

**Issue by mybaseball52** [jlord/git-it#238]
No should like this
http://github.com/githubusername/repositoryname

**Comment by JJ** [comment]
Actually, that is the address for the GitHub pages for that particular repo. as in jlord.github.io/git-it

**Comment by jlord** [comment]
> that is the address for the GitHub pages for that particular repo

Yep, one is the address for the repository on GitHub, one is the address for the website for a repository. 

- Repo: github.com/jlord/git-it
- Website: jlord.github.io/git-it
